Add authentication
Thomah/boothby pull request #26
Opened 2019-02-13 15:45 UTC by JimmyDore

## Status
**READY**

## Migrations
YES
a collection 'user' has been added.

## Description
Added an authentication system in the app.
The passwords are encrypted.
Each API call will be redirected to the auth page, if the user is not authenticated.
To check if a user is authenticated, a token is stored in the server cache, and this token is stored in the session (client-side). Each request will send have this token in the request header.
A function has been written to override the XMLHttpRequest calls, and all the calls have been rewritten using this function.
Schemas of the general behaviour are being drawn. 

## Todos
- [ ] Tests
- [ ] Documentation

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

You must have a user to be able to auth a first time.
Add a collection user in the mongodb.
In the router.js file, uncomment the line 441, and comment the line 440 : 
you should be able to add a user via localhost:8080/add-user.html.
(We unlock the route /api/user with POST method) 
Once the user is created, put the lines the way they were before, restart the server, and you can log in to the application.

```sh
git pull --prune
git checkout <feature_branch>
```

2019-02-14 13:40 UTC, Thomah commented
I had some issues while installing the bcrypt dependency on Windows.
After following [those instructions](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#microsoft-windows), I could execute `npm install` and run the app.

2019-02-15 13:14 UTC, Thomah requested changes
First overview of the PR. It's globally very nice.
Give me a call @JimmyDore if you need to discuss anything :slightly_smiling_face:

2019-02-15 13:14 UTC, Thomah commented on public/html/add-user.html
> +        <label for="uname"><b>Username</b></label>
The value of the for attribute of the label element must be the ID of a non-hidden form control.

2019-02-15 13:14 UTC, Thomah commented on public/html/add-user.html
> +        <label for="psw"><b>Password</b></label>
The value of the for attribute of the label element must be the ID of a non-hidden form control.

2019-02-15 13:14 UTC, Thomah commented on public/html/auth.html
> +        <label for="uname"><b>Username</b></label>
The value of the for attribute of the label element must be the ID of a non-hidden form control.

2019-02-15 13:14 UTC, Thomah commented on public/html/auth.html
> +        <label for="psw"><b>Password</b></label>
The value of the for attribute of the label element must be the ID of a non-hidden form control.

2019-02-15 13:14 UTC, Thomah commented on public/js/auth.js
> +    "GET",
The method "POST" is preferred for login operation :
[https://stackoverflow.com/questions/5868786/what-method-should-i-use-for-a-login-authentication-request](https://stackoverflow.com/questions/5868786/what-method-should-i-use-for-a-login-authentication-request)

As `/api/user` is already taken, maybe use something like `/api/user/login` for this particular endpoint.

2019-02-15 13:14 UTC, Thomah commented on src/router.js
> +             //On stocke dans le serveur en cache le user et le token associé
Nice french comment :smile:

2019-02-15 13:14 UTC, Thomah commented on public/js/index.js
> +//FIX ME : BUG FOUND --> Function not working (even before refactoring) Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
The index page is like a playground. Features on this page are not prioritized (maybe in a loooooong time).

2019-02-15 13:14 UTC, Thomah commented on src/router.js
> +    username = request.headers.username;
Is it possible not to send username in headers ? I think of something like this :
Store every token in a table inside a single spot of the NodeJS cache. Same in the browser cache.

2019-02-15 13:14 UTC, Thomah commented on src/router.js
> +    token = request.headers.token;
I'm annoying I know. But HTTP Headers are often beginning with an uppercase.. :innocent: 
![2019_02_15 - 14_07_01 - accueil](https://user-images.githubusercontent.com/5090230/52858680-1cea9080-312b-11e9-93cf-68a7e8331764.png)

2019-02-15 13:14 UTC, Thomah commented on src/router.js
> +                  //console.log( success );
A dead code ! Not on my watch !

2019-02-15 13:20 UTC, Thomah commented
Not needed for this PR :
- Creation of a default admin user
- Validation of auth form with the enter key
- Encrypt password on client side

2019-02-18 09:05 UTC, JimmyDore commented on public/js/index.js
> +//FIX ME : BUG FOUND --> Function not working (even before refactoring) Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
Ok, so I have to remove this comment ?

2019-02-18 10:16 UTC, Thomah commented on public/js/index.js
> +//FIX ME : BUG FOUND --> Function not working (even before refactoring) Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
Well, the whole feature need to be re-thought so... leave your comment as it is and we'll see later :smile:

2019-02-18 10:20 UTC, JimmyDore commented on public/js/index.js
> +//FIX ME : BUG FOUND --> Function not working (even before refactoring) Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
Too laaaate, I add it again

2019-02-18 12:12 UTC, Thomah requested changes
We're almost there !
We just need to have the browser token stored in cookies not in session. It should solve our problems of multiple tokens in cache.
I also add to the TODO list (not required for the PR) the feature of disconnection.
As usual, don't hesitate to ping me on Slack if you need anything :slightly_smiling_face:

2019-02-18 12:12 UTC, Thomah commented on public/js/request.js
> +    token = sessionStorage.getItem('Token');
Please use cookies instead of session. Checkout my previous review.

2019-02-18 12:12 UTC, Thomah commented on public/js/auth.js
> +      sessionStorage.setItem('Token',token);
I didn't pay attention during the first review but the token should be stored in cookies not in session. So when you reopen your browser, the token is preserved as long as the expiration date is not reached. We can have the token in cache expires at the same moment as the browser cookie.
To manage Vanilla JS cookies, you can check this page : https://www.w3schools.com/js/js_cookies.asp

2019-02-18 15:07 UTC, Thomah approved these changes

2019-02-18 15:12 UTC, merged